project:
  type: website
  output-dir: _site

website:
  title: "Registerbaseret forskning på DST"
  description: "Vejledning til registerbaseret kohortestudie på Danmarks Statistik"
  search: true

  navbar:
    left:
      - href: index.qmd
        text: Forside
    right:
      - text: "Dansk"
        href: da/index.qmd
      - text: "English"
        href: en/index.qmd

  sidebar:
    - id: da
      title: "Indhold"
      style: "docked"
      collapse-level: 1
      contents:
        - da/index.qmd

        - section: "Generelt"
          contents:
            - da/studieforberedelse.qmd
            - da/ressourcer-og-hjaelp.qmd

        - section: "R og RStudio"
          contents:
            - da/r-intro.qmd
            - da/datastrukturer.qmd
            - da/basiskommandoer.qmd
            - da/filformater.qmd

        - section: "DST-serveren"
          contents:
            - da/getting-started-dst.qmd
            - da/parquet-arrow-duckdb.qmd

        - section: "Kode og data"
          contents:
            - da/foerste-udtraek.qmd
            - da/guide_til_funktioner.qmd
            - da/joins-og-pivots.qmd
            - da/formateringstabeller.qmd
            - da/hospitalskontakter-lpr.qmd
            - da/socioekonomiske-variable.qmd

        - section: "Pakker og algoritmer"
          contents:
            - da/pakker-oversigt.qmd
            - da/osdc.qmd
            - da/nmi.qmd
            - da/sepline.qmd

        - section: "Reference"
          contents:
            - da/register_reference.qmd
            - da/dst_faldgruber.qmd

        - section: "Hjemsendelse"
          contents:
            - da/eksport-hjemsendelse.qmd

        - section: "Projekt 708421 (DARTER)"
          contents:
            - da/darter/index.qmd
            - da/darter/registersti-datastores.qmd
            - da/darter/darter-faldgruber.qmd

    - id: en
      title: "Guide"
      style: "docked"
      collapse-level: 1
      contents:
        - en/index.qmd

  back-to-top-btn: true

  page-footer:
    center: "Steno Diabetes Center Aarhus"

format:
  html:
    theme:
      - flatly
      - custom.scss
    toc: true
    toc-depth: 3
    toc-title: "På denne side"
    highlight-style: github
    code-fold: false
    lightbox: true
